---
abstract: '[One line description of module''s purpose here]'
author:
  - 'Chris Prather  C<< <perigrin@cpan.org> >>'
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Wiki-Toolkit-Formatter-Markdown
no_index:
  directory:
    - ex
    - inc
    - t
requires:
  Mouse: 0.10
  Text::Markdown: 1.0.22
resources:
  license: http://dev.perl.org/licenses/
version: 0.0.1
